-- 数据库初始化脚本
-- V20250809__数据库初始化.sql

-- 位置数据表
CREATE TABLE T_LOCATION (
    TID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主键ID
    DEVICE_ID VARCHAR(100) NOT NULL, -- 设备唯一标识
    LATITUDE REAL NOT NULL, -- 纬度
    LONGITUDE REAL NOT NULL, -- 经度
    ACCURACY REAL, -- 精度(米)
    ALTITUDE REAL, -- 海拔(米)
    SPEED REAL, -- 速度(米/秒)
    BEARING REAL, -- 方向角度
    PROVIDER VARCHAR(20) NOT NULL, -- 位置提供者(gps/network/fused)
    LOCATION_TIMESTAMP INTEGER NOT NULL, -- 位置时间戳(毫秒)
    CREATE_TIME INTEGER DEFAULT (strftime('%s', 'now') * 1000), -- 创建时间(毫秒时间戳)
    UPDATE_TIME INTEGER DEFAULT (strftime('%s', 'now') * 1000) -- 更新时间(毫秒时间戳)
);

-- 设备信息表
CREATE TABLE T_DEVICE (
    TID INTEGER PRIMARY KEY AUTOINCREMENT, -- 主键ID
    DEVICE_ID VARCHAR(100) UNIQUE NOT NULL, -- 设备唯一标识
    ANDROID_ID VARCHAR(100), -- Android设备ID
    DEVICE_MODEL VARCHAR(100), -- 设备型号
    OS_VERSION VARCHAR(50), -- 操作系统版本
    APP_VERSION VARCHAR(20), -- 应用版本
    LOCATION_INTERVAL INTEGER DEFAULT 30000, -- 位置获取间隔(毫秒)
    UPLOAD_INTERVAL INTEGER DEFAULT 50000, -- 数据上传间隔(毫秒)
    CREATE_TIME INTEGER DEFAULT (strftime('%s', 'now') * 1000), -- 创建时间(毫秒时间戳)
    UPDATE_TIME INTEGER DEFAULT (strftime('%s', 'now') * 1000), -- 更新时间(毫秒时间戳)
    LAST_SEEN_AT INTEGER -- 最后活跃时间(毫秒时间戳)
);

-- 创建索引优化查询性能
CREATE INDEX IDX_T_LOCATION_DEVICE_ID ON T_LOCATION(DEVICE_ID);
CREATE INDEX IDX_T_LOCATION_TIMESTAMP ON T_LOCATION(LOCATION_TIMESTAMP);
CREATE INDEX IDX_T_LOCATION_CREATE_TIME ON T_LOCATION(CREATE_TIME);
CREATE INDEX IDX_T_DEVICE_DEVICE_ID ON T_DEVICE(DEVICE_ID);

-- 创建触发器自动更新 UPDATE_TIME
CREATE TRIGGER TRIGGER_T_LOCATION_UPDATE_TIME
    AFTER UPDATE ON T_LOCATION
BEGIN
    UPDATE T_LOCATION SET UPDATE_TIME = (strftime('%s', 'now') * 1000) WHERE TID = NEW.TID;
END;

CREATE TRIGGER TRIGGER_T_DEVICE_UPDATE_TIME
    AFTER UPDATE ON T_DEVICE
BEGIN
    UPDATE T_DEVICE SET UPDATE_TIME = (strftime('%s', 'now') * 1000) WHERE TID = NEW.TID;
END;
