# 应用基础配置
spring:
  application:
    name: location-tracker-server
  
  # 数据库配置 - SQLite
  datasource:
    url: jdbc:sqlite:${app.data.path:./data}/location_tracker.db
    driver-class-name: org.sqlite.JDBC
    
  # MyBatis-Plus配置
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.seeker.locationtracker.model.entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
    global-config:
      db-config:
        id-type: AUTO
        table-underline: true
        
  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    
  # 多环境配置
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain

# Swagger配置
swagger:
  enable: true
  
# 日志配置
logging:
  level:
    com.seeker.locationtracker: INFO
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/location-tracker.log
    max-size: 10MB
    max-history: 30

# Actuator监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      simple:
        enabled: true

# 应用自定义配置
app:
  # 数据存储配置
  data:
    path: ${APP_DATA_PATH:./data}  # 数据文件存储路径
    
  # 位置数据配置
  location:
    retention-days: 30
    max-batch-size: 100
    default-location-interval: 30000
    default-upload-interval: 50000
    
  # 安全配置
  security:
    rate-limit:
      upload-per-minute: 60
      query-per-minute: 100
      config-per-minute: 10
