# 双向SSL配置示例
server:
  port: 8443
  ssl:
    enabled: true
    # 服务器证书
    key-store: classpath:ssl/server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: server
    
    # 客户端证书验证
    client-auth: need  # 要求客户端证书
    trust-store: classpath:ssl/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3

# 这种配置下，客户端必须提供有效证书才能连接
